### ISSUE TITLE
Enable this for non-jailbreaken iOSs

### ISSUE THREAD

**Issue by Willian-Zhang** [songchenwen/FaceTimeAudioEnabler#1]
Is the working code actually？
https://github.com/songchenwen/FaceTimeAudioEnabler/blob/master/Tweak.xm

I'm wondering if non-jailbreaken devices can be hooked.

For ref:
`http://stackoverflow.com/questions/27161171/can-you-hook-into-system-function-calls-in-ios-using-private-apis` says no
`https://github.com/steipete/Aspects` implements `swizzling`
`http://blog.csdn.net/hursing/article/details/8688860` i dont know what this is talking about

**Comment by songchenwen** [comment]
Yes, that's the working code. You can only hook the app in the same sandbox with your hooking code on non-jailbroken devices, which means if you want to hook FaceTime.app, you need to jailbreak your device.
